version: '3.5' 

services: 
    backend_service:
      image: backend-example
      ports: 
        - 8000:8000
      container_name: backend_container
      environment: 
        - FRONT_URL=http://localhost:5000
        - REDIS=redis
        - REDIS_PORT=6379
    redis:
      image: redis:5.0.7
    frontend_service:
      image: frontend-example
      ports: 
        - 5000:5000
      environment:
        - API_URL=http://localhost:8000

