version: '3.5' 

services: 

    proxy:
      image: jwilder/nginx-proxy
      volumes:
        - /Users/kasperi/Documents/university/devops-with-docker/part2_ex08/nginx.conf:/etc/nginx/nginx.conf
        - /var/run/docker.sock:/tmp/docker.sock:ro
      ports: 
        - 80:80

    backend_service:
      image: backend-example
      ports: 
        - 8000:8000
      environment: 
        - FRONT_URL=frontend_service:5000
        - REDIS=redis
        - REDIS_PORT=6379

    redis:
      image: redis:5.0.7

    frontend_service:
      image: frontend-example
      ports: 
        - 5000:5000
      environment:
        - API_URL=backend_service:8000

