version: '3.5' 

services: 

    proxy:
      image: jwilder/nginx-proxy
      volumes:
        - /Users/kasperi/Documents/university/devops-with-docker/part2_ex10/nginx.conf:/etc/nginx/nginx.conf
        - /var/run/docker.sock:/tmp/docker.sock:ro
      ports: 
        - 80:80
      depends_on: 
        - db

    backend_service:
      image: backend-example
      ports: 
        - 8000:8000
      environment: 
        - REDIS=redis
        - REDIS_PORT=6379
        - DB_HOST=db
        - DB_NAME=postgres_db
        - DB_USERNAME=admin
        - DB_PASSWORD=1234
      depends_on: 
        - db

    redis:
      image: redis:5.0.7

    frontend_service:
      image: frontend-example
      ports: 
        - 5000:5000
      environment:
        - API_URL=api

    db:
      image: postgres
      restart: unless-stopped
      environment:
        - POSTGRES_DB=postgres_db
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=1234
      volumes:
        - /Users/kasperi/Documents/university/devops-with-docker/part2_ex10/database:/var/lib/postgresql/data
